### ISSUE TITLE
How to change the font size ? Bonus: doing that based on screen resolution

### ISSUE THREAD

**Issue by paolomainardi** [ErikReider/SwayNotificationCenter#108]
HI and thanks for this super cool project!

I wanted to know if there is a way to set a font-size and maybe changing it based on screen resolution or based on output identifier, like waybar does:

ref: https://github.com/Alexays/Waybar/wiki/Styling#per-output-styling
```css
* { font-size: 13px; }
window.eDP-1 * { font-size: 10px; }
```

I am asking this because the standard css on a laptop screen of 14" with a 2k resolution takes half of the screen and it looks everything way bigger than it should.
