### ISSUE TITLE
Width of NC is halved after update to `v1.6.1`

### ISSUE THREAD

**Issue by tukusejssirs** [ErikReider/SwayNotificationCenter#125]
After yesterday’s update, I noticed that the NC width (when open) is halved. The notification itself (when it appears) has the expected size though.

As I understand it, `notification-window-width` configuration changes the size of NC. I have set it to `500`, but even when I change it to `1000`, the size of NC does not change.

Note that I haven’t changed the config before or after the upgrade.

I use `swaync` on Arch Linux with `sway@1.8` built from `master` branch (installed using `sway-git`; commit `440d0bc2`).

<img src='https://user-images.githubusercontent.com/5111894/168475023-bcfd24ca-ef44-4320-89af-9d00e4fb6a73.png' width='48%' alt='Notification'> <img src='https://user-images.githubusercontent.com/5111894/168475024-6b16ac4a-5dfa-4133-b2a8-1dca02ed1770.png' width='48%' alt='Notification centre'>

<details>
   <summary><code>config.json</code></summary>

```json
{
  "$schema": "/etc/xdg/swaync/configSchema.json",
  "positionX": "right",
  "positionY": "top",
  "control-center-margin-top": 5,
  "control-center-margin-bottom": 5,
  "control-center-margin-right": 5,
  "control-center-margin-left": 0,
  "timeout": 7,
  "timeout-low": 3,
  "timeout-critical": 0,
  "notification-window-width": 500,
  "keyboard-shortcuts": true,
  "image-visibility": "always",
  "transition-time": 200,
  "hide-on-clear": false,
  "hide-on-action": true,
  "script-fail-notify": true,
  "scripts": {
    "example-script": {
      "exec": "echo 'Do something...'",
      "urgency": "Normal"
    }
  },
  "notification-visibility": {
    "example-name": {
      "state": "muted",
      "urgency": "Low",
      "app-name": "Spotify"
    }
  }
}
```

</details>

<details>
   <summary><code>style.css</code></summary>

```css
@define-color border-color rgb(7, 7, 7);
@define-color bg rgb(58, 58, 58);
@define-color bg-hover rgb(68, 68, 68);
@define-color bg-focus rgba(68, 68, 68, 0.6);
@define-color bg-selected rgb(0, 128, 255);

.notification-row {
  outline: none;
}
.notification-row:focus,
.notification-row:hover {
  background: @bg-focus;
}

.notification {
  border-radius: 10px;
  margin: 6px 12px;
  box-shadow: 0px 2px 4px 2px rgba(0, 0, 0, 0.3);
  padding: 0;
}

.notification-content {
  /*background: sol;*/
  padding: 6px;
  border-radius: 10px;
}

.close-button {
  background: black;
  color: white;
  text-shadow: none;
  padding: 0 2px;
  box-shadow: 0px 2px 4px 2px rgba(0, 0, 0, 0.3);
  border-radius: 100%;
}
.close-button:hover {
  background: rgb(30, 30, 30);
  transition: all 0.15s ease-in-out;
}

.notification-default-action,
.notification-action {
  padding: 4px;
  margin: 0;
  box-shadow: none;
  background: @bg;
  border: 1px solid @border-color;
}

.notification-default-action:hover,
.notification-action:hover {
  background: @bg-hover;
}

.notification-default-action {
  border-radius: 10px;
}

/* When alternative actions are visible */
.notification-default-action:not(:only-child) {
  border-bottom-left-radius: 0px;
  border-bottom-right-radius: 0px;
}

.notification-action {
  border-radius: 0px;
  border-top: none;
  border-right: none;
}

/* add bottom border radius to eliminate clipping */
.notification-action:first-child {
  border-bottom-left-radius: 10px;
}
.notification-action:last-child {
  border-bottom-right-radius: 10px;
  border-right: 1px solid @border-color;
}

.image {
}

.body-image {
  margin-top: 6px;
  background-color: white;
  border-radius: 10px;
}

.summary {
  color: white;
  text-shadow: none;
}

.time {
  color: white;
  text-shadow: none;
}

.body {
  background: transparent;
  color: white;
  text-shadow: none;
}

.top-action-title {
  color: white;
  text-shadow: none;
}

.control-center-clear-all {
  color: white;
  text-shadow: none;
  background: @bg;
  border: 1px solid @border-color;
  box-shadow: none;
  border-radius: 10px;
}
.control-center-clear-all:hover {
  background: @bg-hover;
}

.control-center-dnd {
  border-radius: 10px;
  background: @bg;
  border: 1px solid @border-color;
  box-shadow: none;
}

.control-center-dnd:checked {
  background: @bg-selected;
}
.control-center-dnd slider {
  background: @bg-hover;
}

.control-center {
  background: rgba(0, 0, 0, 0.7);
}
.control-center-list {
  background: transparent;
}

.floating-notifications {
  background: transparent;
}
```

</details>
