### ISSUE TITLE
Unable to change the font size of notification .summary

### ISSUE THREAD

**Issue by nostdm** [ErikReider/SwayNotificationCenter#143]
**Swaync version:** `0.6.3`
**Sway version:** `1.7`

I'm trying to change the font size of the title/summary of the notification bubble.

I'm able to change font-size of the `.body` of the notification without any issues:

```css
.body {
  background: transparent;
  color: white;
  font-family: "Roboto";
  font-size: 20px;
  text-shadow: none;
}
```

![image](https://user-images.githubusercontent.com/16334589/178292472-8e6bf547-7250-435e-a29c-10c762f44894.png)

But changing the font-size of the `.summary` part of the notification has no effect:

```css
.summary {
  color: white;
  font-family: "Roboto";
  font-size: 22px;
  text-shadow: none;
}
```

![image](https://user-images.githubusercontent.com/16334589/178293101-052c41c4-2b3d-4d00-9694-7d4e8d173841.png)

I can also change other styles of the summary just fine:

```css
.summary {
    color: red;
    ...
}
```

![image](https://user-images.githubusercontent.com/16334589/178295162-c2da8444-1132-411a-a612-148d825e8429.png)

I tried debugging with `GTK_DEBUG=interactive swaync` and it shows that the CSS of the `.summary` node is being applied but it has no visual effect. Unless there's some other CSS style that is overriding it?
