### ISSUE TITLE
[Bug] floating-notifications have artefacts around

### ISSUE THREAD

**Issue by fybx** [ErikReider/SwayNotificationCenter#335]
**Describe the bug**
A gray/black artefact is present around every `.floating-notifications` instance.

![image](https://github.com/ErikReider/SwayNotificationCenter/assets/41127439/5c418881-0be9-489a-a9a4-adee464bc1e9)

**To Reproduce**
1. Start a [hyprland](https://github.com/hyprwm/hyprland) desktop session
2. Set `.floating-notifications { background: transparent; }` in `style.css`
3. Get a notification

**Expected behavior**
The notifications must have clear borders.

**Please provide logs if you're experiencing notification errors / bugs**
Not applicable.

**Screenshots**
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/41127439/15c1f64b-ca2a-4ee6-86ee-ff926cd0b47e)

**Desktop (please complete the following information):**
 - OS: Arch Linux GNU/Linux 6.1.62-1-lts
 - Version: swaync 0.9.0 (git-175699d, branch 'master')

**Additional context**

I have used `GTK_DEBUG=interactive swaync` to debug the layout and pinpointed the `.background` class to set the floating notification's backgrounds. I can change the colors, or set it to transparent. Even when set to transparent, the artefacts stay.

---

This SCSS file is transpiled to the `style.css` file for swaync-client.

```scss
/* Window behind control center and on all other monitors */
.blank-window {
    // Keeping it transparent for applying layerrule blur in hyprland
    background: transparent;
}

.control-center {
    background: $clrTrayBackground;
    border-radius: 24px;
    padding: $pxTrayInnerPadding;
}

.floating-notifications {
    background: transparent;
}

.background {
    background: transparent;
}

.notification-row {
    background: transparent;
}
```

---

And this is the `hyprland.conf` file to ignore transparent layers:

```
    layerrule = ignorezero, swaync-notification-window
```
