### ISSUE TITLE
[Question] mpris player buttons style configuration

### ISSUE THREAD

**Issue by godfuzz3r** [ErikReider/SwayNotificationCenter#365]
May be it's a stupid quistion, but I can't find any example for configuring mpris player buttons in the center (previous track, play/pause, next track):
![image](https://github.com/ErikReider/SwayNotificationCenter/assets/24232540/04002cfd-7945-4ef2-8f8a-633fc8c93746)

I'd like to change them to white colors. Current css for mpris widget:
```css
.widget-mpris {

}
.widget-mpris-player {
    padding: 3px 6px;
    margin: 5px;
}
.widget-mpris-title {
    font-weight: 300;
}

.widget-mpris-subtitle {
    font-size: 0.75rem
}
```
