### ISSUE TITLE
[Bug] Can't disable mpris background cover

### ISSUE THREAD

**Issue by zDyanTB** [ErikReider/SwayNotificationCenter#422]
As the title says, I can't disable this blurred background cover. Everything but a 100% opaque color will turn this background into the cover.

Code
```css

  /* Music player */
.widget-mpris {
    color: @text;
    margin:  20px 0px;
}

  /* NOTE: Background need *opacity 1* otherwise will turn into the album art blurred  */
.widget-mpris-player {
   /* background: @selected; */
    border-radius: 16px;
    padding: 6px 12px;
    margin: 8px;
}

.widget-mpris > box > button {
  color: red;
  border-radius: 20px;
}
 
.widget-mpris button {
  color: alpha(@text, .6);
}

.widget-mpris button:hover {
  color: @text;
}


.widget-mpris-album-art {
  border-radius: 16px;
}
 
.widget-mpris-title {
    font-weight: 700;
    font-size: 1rem;
}
 
.widget-mpris-subtitle {
    font-weight: 500;
    font-size: 0.8rem;
}

```
Is there a way to configure to use a color somewhat transparent or disable it completely?

![image](https://github.com/ErikReider/SwayNotificationCenter/assets/102763838/e9fceea1-8a54-41bb-b6c7-fd243cc6b20d)

 - OS: NixOs
 - Version: 23.11
