### ISSUE TITLE
change slider thickness [Feature]

### ISSUE THREAD

**Issue by Anik200** [ErikReider/SwayNotificationCenter#458]
**Please read through the README and the Man pages before submitting**
**Please also make sure that there isn't any prior issue describing this feature**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/44499de8-dc62-4df9-bf10-6bf62362e485)
is there any way to chnage the thickness of the sliders

**Describe alternatives you've considered**

**Additional context**

**Comment by ErikReider** [comment]
That would be through custom CSS styling :)

**Comment by Anik200** [comment]
Please a bit of an example since i have no custom css experience 
> That would be through custom CSS styling :)

**Comment by retrozinndev** [comment]
> Please a bit of an example since i have no custom css experience

You can use padding in the `highlight` element.
```css
trough highlight { /* ´trough´ is the background of the slider, ´highlight´ is the actual slider */
    padding: 5px;
}
```

**Comment by Anik200** [comment]
![image](https://github.com/user-attachments/assets/5b1c3ae8-b56d-4a6b-9fb1-354e0323047b)


> > Please a bit of an example since i have no custom css experience
> 
> You can use padding in the `highlight` element.
> 
> ```css
> trough highlight { /* ´trough´ is the background of the slider, ´highlight´ is the actual slider */
>     padding: 5px;
> }
> ```

that didn't do anything

**Comment by Anik200** [comment]
![image](https://github.com/user-attachments/assets/ec614455-d3f7-49f5-95bb-5295b5da27ea)
 i tried this too but same

**Comment by Anik200** [comment]
no worries it worked but how do i increase the size of the knob
![image](https://github.com/user-attachments/assets/25c64852-e625-4df7-a82b-35e3c10b8990)

**Comment by retrozinndev** [comment]
> no worries it worked but how do i increase the size of the knob 

I do not know the name of the element, but I think you can do so like this:
```css
trough highlight > *:first-child {
    padding: 5px;
}
```

**Comment by retrozinndev** [comment]
I just found out, the knob is the `slider` element, you can put it like this:
```css
trough highlight slider {
     padding: 5px;
}
```

**Comment by Anik200** [comment]
![image](https://github.com/user-attachments/assets/8c729e1c-c6bb-45c1-a3e6-04d7af4ba1d0)


> Actually, I just found out, the knob is the `slider` element, you can put it like this:
> 
> ```css
> trough highlight slider {
>      padding: 5px;
> }
> ```

it didnt work...

**Comment by retrozinndev** [comment]
Curious... It changes the size of all the slider elements... I'll test here and see what I can do about that.

**Comment by retrozinndev** [comment]
Actually, the slider indicator is before the highlight element. You can change it's padding with:
```css
trough slider {
    padding: 5px;
}
```
