### ISSUE TITLE
[Bug] Volume `slider` out of it's expected position

### ISSUE THREAD

**Issue by retrozinndev** [ErikReider/SwayNotificationCenter#487]
**Please read through the README and the Man pages before submitting** ✅ 
**Please also make sure that there isn't any prior issue describing this bug** ✅ 

**Describe the bug**
The volume slider(knob) goes outside of intended position when volume is too low or very high.

**To Reproduce**
1. Add volume slider to widgets list in config JSON
2. Open Control Center Panel
4. Low down volume to less than 4% or more than 97%
5. See the volume slider knob go out of it's position

**Expected behavior**
The slider knob should be inside the `trough`, not outside of it.

**Please provide logs if you're experiencing notification errors / bugs**
No logs, not an error.

**Screenshots**
![2024-11-04-213037_hyprshot](https://github.com/user-attachments/assets/d4a12f52-6fc5-4a22-858b-dac745cfa00a)
![2024-11-04-213049_hyprshot](https://github.com/user-attachments/assets/c5da5b0d-44eb-4344-a634-8e85a265b65b)

**Desktop (please complete the following information):**
 - OS: Arch Linux with Hyprland
 - Version `0.10.1`

**Stylesheet of horizontal sliders**
```css
.horizontal trough { /* slider's background */
    background-color: shade(@color1, .4);
    margin: 0 4px;
    border-radius: 16px;
    padding: 4px;
}

.horizontal trough slider { /* slider's dot indicator */
    background: @foreground;
    box-shadow: inset 0 0 1px .5px @background-alt;
    min-width: 24px;
    min-height: 24px;
    margin-right: 4px;
    border-radius: 50%;
}

.horizontal trough slider:active {
    background: shade(@foreground, .75);
}

.horizontal trough highlight {
    border-top-left-radius: 14px;
    border-bottom-left-radius: 14px;
    background: shade(@highlight, .9);
}
```

**Additional context**
If this is intentional, is there a way to workaround the `slider`'s position? Like changing its margin if volume is lower/higher, using a CSS class.
In the default stylesheet that SwayNC has, i see the `slider` being bigger than the `highlight` element, but I cannot achieve the same result with my stylesheet, for some reason.

**Comment by ErikReider** [comment]
This is due to your GTK theme messing with swaync, so you'll have to add fixes to your CSS config file. There's sadly nothing that I can do about it, but there are tips in the README for debugging and such

**Comment by retrozinndev** [comment]
Ok, thanks for the fast answer! I'll try using the `GTK_THEME` variable to run SwayNC with the default theme. If it works, I'll put the result here.

**Comment by retrozinndev** [comment]
Tried using the `GTK_THEME` env variable, but no success, also tried setting the default theme for gtk3 apps to Default Adwaita, but unfortunately, I got the same result:
![image](https://github.com/user-attachments/assets/6104c632-3ea4-404d-9682-3a1b38a7c443)

**Comment by ErikReider** [comment]
> Tried using the `GTK_THEME` env variable, but no success, also tried setting the default theme for gtk3 apps to Default Adwaita, but unfortunately, I got the same result:

Might be that you have custom CSS in your ~/.config/gtk-3.0/ directory?

**Comment by retrozinndev** [comment]
No, I don't have any custom css inside `.config/gtk-3.0`:
![image](https://github.com/user-attachments/assets/ec7fc0a0-ac81-4e4d-a9c6-a9c0cc9bb135)

If useful, I'm using `all: unset` for every element (`*`) in the control center, so it doesn't take default styling by gtk theme. Should I not use it?

**Comment by ErikReider** [comment]
Wait, is the CSS that you initially posted something that you wrote to make the progressbar look that way?

**Comment by retrozinndev** [comment]
Yes!

**Comment by retrozinndev** [comment]
Just did some testing with styles and found out how to make the `slider` bigger than the `highlight`!
![image](https://github.com/user-attachments/assets/63561eae-dfbd-4d29-9248-de71ce740b39)
```css
.horizontal trough slider {
    margin: -5px;
}
```
I just needed to put a negative margin to the `slider` element and it just "detached" from the `highlight` element. Somehow, doing this makes it not to show much that the slider is going out of the `trough` element.
