### ISSUE TITLE
[Bug] Action buttons styling breaks after GTK 4 port

### ISSUE THREAD

**Issue by S0nter** [ErikReider/SwayNotificationCenter#543]
### **Describe the bug**
After [GTK 4 port](https://github.com/ErikReider/SwayNotificationCenter/commit/3d719a829425d41c00e4e09dd1f5f77e64dfbfd5) some configurations from [config flex](https://github.com/ErikReider/SwayNotificationCenter/discussions/183) are broken

### **To Reproduce**
1. Initial setup

```shell
git clone https://github.com/ErikReider/SwayNotificationCenter && cd SwayNotificationCenter
git checkout f55b433e05bf2f7d9772b86a9f613571efc3ae34

meson setup build
```

2. Compile

```shell
# Compile
meson compile -Cbuild

# Run with the default config and provided style
./build/src/swaync -s style.css -c ./build/src/config.json
```

3. Send test notification
```shell
notify-send --app-name='Multiline
Application Name' \
                --icon=bell \
                -A action1 -A action2 -A action3 \
                'Multiline
summary' \
                'Multiline
notification
body'
```

### **Expected behavior**
Action buttons styling would continue working

### **Screenshots**

Commit [`5a6ae71d95f2925463a05933467e3faf8c1a000e`](https://github.com/ErikReider/SwayNotificationCenter/commit/5a6ae71d95f2925463a05933467e3faf8c1a000e) (Before GTK 4 port)

![Image](https://github.com/user-attachments/assets/d387adb2-b41f-4be5-8f8f-851b4b0ed888)

Commit [`f55b433e05bf2f7d9772b86a9f613571efc3ae34`](https://github.com/ErikReider/SwayNotificationCenter/commit/f55b433e05bf2f7d9772b86a9f613571efc3ae34) (After GTK 4 port)

![Image](https://github.com/user-attachments/assets/94af2e69-2395-45c0-933c-cca4f8e75683)

### **Additional context**
Potential causes:

```css
* {
  all: unset;
}
... > *:last-child > * ... { ... }
```

### Style

```css
@define-color text            #c6d0f5;
@define-color background-alt  #99d1db;
@define-color background      #99d1db;
@define-color selected        #81c8be;
@define-color hover           #85c1dc;
@define-color urgent          #e78284;

* {
    color: @text;
    all: unset;
    font-size: 14px;
    font-family: "JetBrains Mono Nerd Font 10";
    transition: 200ms;

}

.notification-row {
    outline: none;
    margin: 0;
    padding: 0px;
}

.floating-notifications.background .notification-row .notification-background {
    background: alpha(@background, .55);
    box-shadow: 0 0 8px 0 rgba(0,0,0,.6);
    border: 1px solid @selected;
    border-radius: 24px;
    margin: 16px;
    padding: 0;
}

.floating-notifications.background .notification-row .notification-background .notification {
    padding: 6px;
    border-radius: 12px;
}

.floating-notifications.background .notification-row .notification-background .notification.critical {
    border: 2px solid @urgent;
}

.floating-notifications.background .notification-row .notification-background .notification .notification-content {
    margin: 14px;
}

.floating-notifications.background .notification-row .notification-background .notification > *:last-child > * {
    min-height: 3.4em;
}

.floating-notifications.background .notification-row .notification-background .notification > *:last-child > * .notification-action {
    border-radius: 8px;
    background-color: @background-alt ;
    margin: 6px;
    border: 1px solid transparent;
}

.floating-notifications.background .notification-row .notification-background .notification > *:last-child > * .notification-action:hover {
    background-color: @hover;
    border: 1px solid @selected;
}

.floating-notifications.background .notification-row .notification-background .notification > *:last-child > * .notification-action:active {
    background-color: @selected;
    color: @background;
}

.summary {
    font-weight: 800;
    font-size: 1rem;
}

.body {
    font-size: 0.8rem;
}

.floating-notifications.background .notification-row .notification-background .close-button {
    margin: 6px;
    padding: 2px;
    border-radius: 6px;
    background-color: transparent;
    border: 1px solid transparent;
}
```
